spring.application.name=uploadTest
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB
server.port=${PORT:8080}
